language: node_js
node_js:
  - 9
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn test
cache:
  directories:
    - "node_modules"
after_success:
  - codecov
deploy:
  provider: npm
  email: echoulen@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
